kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: "mediawiki-ns"
  name: mediawiki-sc
  labels:
    {{- include "storage.labels" . | nindent 4 }}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

